title: What to do after a death
email: tjharrop@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Steps to take and when to take them
baseurl: "/endoflife" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tjharrop
github_username:  tjharrop
stage: alpha

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

remote_theme: tjharrop/NSW-jekyll-theme
